name: torch_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - ujson
  - numpy
  - pandas
  - pip
  - spacy
  - tensorboard=2.4
  - tensorboardX=2.2
  - tqdm
  - urllib3
  - pytorch=1.7.1
  - matplotlib
  - networkx=2.5
  - cudatoolkit=10.2
  - torchvision=0.8
  - scikit-learn=0.24
  - scikit-image=0.18
  - rpy2